# Generated by Django 5.2.4 on 2025-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='breadcrumbs',
            field=models.JSONField(default=list, help_text='Breadcrumb navigation data'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='meta_tags',
            field=models.JSONField(default=dict, help_text='Additional meta tags'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='open_graph_tags',
            field=models.JSONField(default=dict, help_text='Open Graph tags for social media'),
        ),
    ]
