blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yourusername/sarkaribot/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📧 Security Issues
    url: mailto:security@sarkaribot.com
    about: Report security vulnerabilities privately
  - name: 📖 Documentation
    url: https://github.com/yourusername/sarkaribot/tree/main/docs
    about: Check our comprehensive documentation
