name: ❓ Question
description: Ask a question about SarkariBot
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about SarkariBot? We're here to help! Please provide as much context as possible.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Features
        - API & Integration
        - Development & Contributing
        - Deployment
        - Troubleshooting
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context for your question.
      placeholder: What are you trying to accomplish? What have you already tried?

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: If relevant, provide details about your environment.
      placeholder: |
        - OS: 
        - Python version: 
        - Node.js version: 
        - Browser: 
        - Other relevant details:

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful.
      placeholder: Screenshots, error messages, configuration files, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation for answers to my question
          required: true
        - label: This is not a bug report (use the bug report template for those)
          required: true
