# Generated by Django 4.2.14 on 2025-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordtracking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='keywordtracking',
            name='seo_keyword_current_8d0945_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordtracking',
            name='seo_keyword_is_targ_ef6a0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordtracking',
            name='seo_keyword_last_ch_fdf126_idx',
        ),
        migrations.RemoveIndex(
            model_name='seometadata',
            name='seo_seometa_generat_faf144_idx',
        ),
        migrations.RemoveIndex(
            model_name='seometadata',
            name='seo_seometa_quality_8d851f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='keywordtracking',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='keywordtracking',
            index=models.Index(fields=['-search_volume'], name='seo_keyword_search__22e637_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordtracking',
            index=models.Index(fields=['-difficulty_score'], name='seo_keyword_difficu_1fd2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='seometadata',
            index=models.Index(fields=['title'], name='seo_seometa_title_07c340_idx'),
        ),
        migrations.AddIndex(
            model_name='seometadata',
            index=models.Index(fields=['-updated_at'], name='seo_seometa_updated_1edefe_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemapentry',
            index=models.Index(fields=['url'], name='seo_sitemap_url_76a4c3_idx'),
        ),
    ]
