# Generated by Django 4.2.14 on 2025-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='governmentsource',
            name='sources_gov_active_950c14_idx',
        ),
        migrations.RenameField(
            model_name='governmentsource',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddIndex(
            model_name='governmentsource',
            index=models.Index(fields=['is_active', 'status'], name='sources_gov_is_acti_21b179_idx'),
        ),
    ]
